---
title: "Modern concepts and methods in Macroecology and Biogeography"
author: "Patrick Weigelt, Pierre Denelle, Amanda Taylor & Holger Kreft"
output: 
  html_document: 
    theme: flatly
    toc: yes
---

## 1. Overview

Here we provide links to the tutorials of the "Modern concepts and methods in Macroecology and Biogeography" class. The tutorials are written as R markdown scripts which can be downloaded at our [github site](https://github.com/patrickweigelt/MCMMB) if interested. The tutorials contain chunks of code that can be run in R, as well as results and figures produced by R, annotations and excercises. Instructions on how to set up R and RStudio, to start a new project and install R packages will be given on the first day. If you wonder why using R, have a look [here](Day1_WhyR.html)! For preparation please install the latest versions of the following programs and always install the R packages indicated at the beginning of each tutarial before the classes start.



QGIS from <https://www.qgis.org/>

R from <http://www.r-project.org/>

RStudio from <https://www.rstudio.com/>


## 2. Links to tutorials

* Day 1: [Basics and spatial data in R](Day1.html)
* Day 2: [data.frames and GIS shapefiles in R; subsetting, joining & aggregating](Day2.html)
* Day 3: [Download point occurrences & fit species distribution models](Day3.html)
* Day 4: [The latitudinal diversity gradient](Day4.html)
* Day 5: [Environmental drivers of neotropical palm diversity](Day5.html)
* Day 6: [Island Biogeography](Day6.html)
* Day 7: [Phylogenetic diversity](Day7.html)
* Day 8: [Functional biogeography](Day8.html)  





